### ISSUE TITLE
db query error: pq: syntax error at or near ")" out of the box

### ISSUE THREAD

**Issue by serjs** [shizunge/blocky-postgresql#1]
Hi!

I'm trying to add PG based dashboard and have problem out of the box in Grafana.

My Grafana version: 9.4.2
Postgres: 14.5
Dashboard rev: 2023-03-05 15:49:40

Out of the box get `db query error: pq: syntax error at or near ")" out of the box` for every panel.

I have no expirience with PG datasource, and don't know hot to debug this error

**Comment by shizunge** [comment]
I do want to help.
1. Where do you get the dashboard? Import from Granada or GitHub?

2. Are client name, dns type, etc, On the top, set to "All"?

3. When you added data source, did you select the correct database name?

**Comment by shizunge** [comment]
![Screenshot_20230305-094851](https://user-images.githubusercontent.com/1281491/222971108-d8048dc3-9e27-46f6-8764-4a35fb366377.png)

**Comment by serjs** [comment]
Hi! Thank you for answers. I'm doing double check everything from your comments.
The problem is in GRANT permissions. I'm doing wrong GRANT to select data from tables. 

It'strange that Grafana showing `db query error: pq: syntax error at or near ")"` in this case.

The way I found issues is making simple query from new panel: `select * FROM log_entries;` That where Grafana says to me about permission problems;

My Final privileges model is: `GRANT SELECT ON TABLE public.log_entries TO grafana;`
where `grafana` is RO user in Postgres
